/*
 * UserDataExtendedWebSoap.java
 *
 * Version $Revision$ $Date$
 *
 * This file is part of ISBJ.
 *
 * Copyright 2017 Senatsverwaltung fuer Bildung, Jugend und Familie, Berlin.
 * Created by Schuetze Consulting AG, Berlin.
 */
package de.scag.demofachverfahren.paasdemo.servicekonto.hhgwuserdata;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 2.4.9 2017-05-18T13:30:34.617+02:00
 * Generated source version: 2.4.9.
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "UserDataExtendedWebSoap")
@XmlSeeAlso({ObjectFactory.class})
@Generated(
        value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-18T13:30:34.617+02:00",
        comments = "Apache CXF 2.4.9"
)
public interface UserDataExtendedWebSoap {
    /**
     * Gets the user data.
     *
     * @param strToken          the str token
     * @param strXMLUserData    the str XML user data
     * @param getUserDataResult the get user data result
     * @return the user data
     */
    @WebMethod(operationName = "GetUserData", action = "http://tempuri.org/GetUserData")
    @RequestWrapper(
            localName = "GetUserData", targetNamespace = "http://tempuri.org/",
            className = "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.GetUserData"
    )
    @ResponseWrapper(
            localName = "GetUserDataResponse", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.GetUserDataResponse"
    )
    @Generated(
            value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-18T13:30:34.617+02:00"
    )
    void getUserData(
            @WebParam(name = "strToken", targetNamespace = "http://tempuri.org/") java.lang.String strToken,
            @WebParam(
                    mode = WebParam.Mode.INOUT, name = "strXMLUserData",
                    targetNamespace = "http://tempuri.org/"
            ) javax.xml.ws.Holder<java.lang.String> strXMLUserData,
            @WebParam(
                    mode = WebParam.Mode.OUT, name = "GetUserDataResult",
                    targetNamespace = "http://tempuri.org/"
            ) javax.xml.ws.Holder<java.lang.Integer> getUserDataResult);

    /**
     * Sets the extended user data.
     *
     * @param lUserID                the l user ID
     * @param lFVID                  the l FVID
     * @param strXMLExtendedUserData the str XML extended user data
     * @return the int
     */
    @WebMethod(
            operationName = "SetExtendedUserData", action = "http://tempuri.org/SetExtendedUserData"
    )
    @RequestWrapper(
            localName = "SetExtendedUserData", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.SetExtendedUserData"
    )
    @ResponseWrapper(
            localName = "SetExtendedUserDataResponse", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.SetExtendedUserDataResponse"
    )
    @WebResult(name = "SetExtendedUserDataResult", targetNamespace = "http://tempuri.org/")
    @Generated(
            value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-18T13:30:34.617+02:00"
    )
    int setExtendedUserData(
            @WebParam(name = "lUserID", targetNamespace = "http://tempuri.org/") long lUserID,
            @WebParam(name = "lFVID", targetNamespace = "http://tempuri.org/") long lFVID,
            @WebParam(name = "strXMLExtendedUserData", targetNamespace = "http://tempuri.org/") java
                    .lang.String strXMLExtendedUserData);

    /**
     * Insert internet user.
     *
     * @param oInternetUserData        the o internet user data
     * @param lUserID                  the l user ID
     * @param strErrorXml              the str error xml
     * @param insertInternetUserResult the insert internet user result
     */
    @WebMethod(
            operationName = "InsertInternetUser", action = "http://tempuri.org/InsertInternetUser"
    )
    @RequestWrapper(
            localName = "InsertInternetUser", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.InsertInternetUser"
    )
    @ResponseWrapper(
            localName = "InsertInternetUserResponse", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.InsertInternetUserResponse"
    )
    @Generated(
            value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-18T13:30:34.617+02:00"
    )
    void insertInternetUser(
            @WebParam(name = "oInternetUserData", targetNamespace = "http://tempuri.org/")
                    InternetUserData oInternetUserData,
            @WebParam(
                    mode = WebParam.Mode.INOUT, name = "lUserID", targetNamespace = "http://tempuri.org/"
            ) javax.xml.ws.Holder<java.lang.Long> lUserID,
            @WebParam(
                    mode = WebParam.Mode.INOUT, name = "strErrorXml",
                    targetNamespace = "http://tempuri.org/"
            ) javax.xml.ws.Holder<java.lang.String> strErrorXml,
            @WebParam(
                    mode = WebParam.Mode.OUT, name = "InsertInternetUserResult",
                    targetNamespace = "http://tempuri.org/"
            ) javax.xml.ws.Holder<java.lang.Integer> insertInternetUserResult);

    /**
     * Sets the extended user data with token.
     *
     * @param strToken               the str token
     * @param strXMLExtendedUserData the str XML extended user data
     * @return the int
     */
    @WebMethod(
            operationName = "SetExtendedUserDataWithToken",
            action = "http://tempuri.org/SetExtendedUserDataWithToken"
    )
    @RequestWrapper(
            localName = "SetExtendedUserDataWithToken", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.SetExtendedUserDataWithToken"
    )
    @ResponseWrapper(
            localName = "SetExtendedUserDataWithTokenResponse", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.SetExtendedUserDataWithTokenResponse"
    )
    @WebResult(name = "SetExtendedUserDataWithTokenResult", targetNamespace = "http://tempuri.org/")
    @Generated(
            value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-18T13:30:34.617+02:00"
    )
    int setExtendedUserDataWithToken(
            @WebParam(name = "strToken", targetNamespace = "http://tempuri.org/") java.lang.String strToken,
            @WebParam(name = "strXMLExtendedUserData", targetNamespace = "http://tempuri.org/") java
                    .lang.String strXMLExtendedUserData);

    /**
     * Insert internet user P.
     *
     * @param strLoginName              the str login name
     * @param strPassword               the str password
     * @param strCity                   the str city
     * @param strCountry                the str country
     * @param strDateOfBirth            the str date of birth
     * @param strEMail                  the str E mail
     * @param strFirstName              the str first name
     * @param strLastName               the str last name
     * @param strLanguage               the str language
     * @param strPrefix                 the str prefix
     * @param strStreet                 the str street
     * @param strStreetNumber           the str street number
     * @param strStreetExtension        the str street extension
     * @param strTitle                  the str title
     * @param strZipCode                the str zip code
     * @param nLevelID                  the n level ID
     * @param lUserID                   the l user ID
     * @param strErrorXml               the str error xml
     * @param insertInternetUserPResult the insert internet user P result
     */
    @WebMethod(
            operationName = "InsertInternetUserP", action = "http://tempuri.org/InsertInternetUserP"
    )
    @RequestWrapper(
            localName = "InsertInternetUserP", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.InsertInternetUserP"
    )
    @ResponseWrapper(
            localName = "InsertInternetUserPResponse", targetNamespace = "http://tempuri.org/",
            className =
                    "de.verwalt_berlin.senbjw.isbj.servicekonto.client.nutzerdaten.InsertInternetUserPResponse"
    )
    @Generated(
            value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-18T13:30:34.617+02:00"
    )
    void insertInternetUserP(
            @WebParam(name = "strLoginName", targetNamespace = "http://tempuri.org/") java.lang.String strLoginName,
            @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/") java.lang.String strPassword,
            @WebParam(name = "strCity", targetNamespace = "http://tempuri.org/") java.lang.String strCity,
            @WebParam(name = "strCountry", targetNamespace = "http://tempuri.org/") java.lang.String strCountry,
            @WebParam(name = "strDateOfBirth", targetNamespace = "http://tempuri.org/") java.lang.String strDateOfBirth,
            @WebParam(name = "strEMail", targetNamespace = "http://tempuri.org/") java.lang.String strEMail,
            @WebParam(name = "strFirstName", targetNamespace = "http://tempuri.org/") java.lang.String strFirstName,
            @WebParam(name = "strLastName", targetNamespace = "http://tempuri.org/") java.lang.String strLastName,
            @WebParam(name = "strLanguage", targetNamespace = "http://tempuri.org/") java.lang.String strLanguage,
            @WebParam(name = "strPrefix", targetNamespace = "http://tempuri.org/") java.lang.String strPrefix,
            @WebParam(name = "strStreet", targetNamespace = "http://tempuri.org/") java.lang.String strStreet,
            @WebParam(name = "strStreetNumber", targetNamespace = "http://tempuri.org/") java.lang.String strStreetNumber,
            @WebParam(name = "strStreetExtension", targetNamespace = "http://tempuri.org/") java.lang.String strStreetExtension,
            @WebParam(name = "strTitle", targetNamespace = "http://tempuri.org/") java.lang.String strTitle,
            @WebParam(name = "strZipCode", targetNamespace = "http://tempuri.org/") java.lang.String strZipCode,
            @WebParam(name = "nLevelID", targetNamespace = "http://tempuri.org/") int nLevelID,
            @WebParam(
                    mode = WebParam.Mode.INOUT, name = "lUserID", targetNamespace = "http://tempuri.org/"
            ) javax.xml.ws.Holder<java.lang.Long> lUserID,
            @WebParam(
                    mode = WebParam.Mode.INOUT, name = "strErrorXml",
                    targetNamespace = "http://tempuri.org/"
            ) javax.xml.ws.Holder<java.lang.String> strErrorXml,
            @WebParam(
                    mode = WebParam.Mode.OUT, name = "InsertInternetUserPResult",
                    targetNamespace = "http://tempuri.org/"
            ) javax.xml.ws.Holder<java.lang.Integer> insertInternetUserPResult);
}
