spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/paas_demo
    url: jdbc:h2:file:~/paas_demo
    username: paas_demo_user
    password: paas_demo_pw
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
servicekonto:
  #  base-url: https://localhost:9081
  base-url: http://localhost:8081
  fachverfahren: 14
  key-store-path: target/test-classes/keystore-service-konto-mock.p12
  trust-store-path: target/test-classes/cacerts.jks
  nachrichten:
    local-part: GovGWAsyncResponse
    path: /GovGWAsyncResponse/GovGWAsyncResponse.wsdl
    target-namespace-uri: http://tempuri.org/
  nutzerdaten:
    local-part: UserDataExtendedWeb
    path: /HHGWUserData/HHGWUserData.wsdl
    target-namespace-uri: http://tempuri.org/
  login-url: http://localhost:8081/app.html
  keystore-password: password
