spring:
  datasource:
    url: jdbc:h2:file:~/paas_demo_dev
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create
    show-sql: true
remember-me-token-config:
  use-secure-cookie: false
